include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - require_trailing_commas
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
