// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PM2MOYe0NdHF9rJb45yhHvLe-_tzIAU',
    appId: '1:1070995801144:web:106ba21adeb7660e4552cd',
    messagingSenderId: '1070995801144',
    projectId: 'mengproject-9eb56',
    authDomain: 'mengproject-9eb56.firebaseapp.com',
    storageBucket: 'mengproject-9eb56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAz7zkN-qDkjc2c4plIwIO4kcbgNZfzig',
    appId: '1:1070995801144:android:217930b2d7c0d1894552cd',
    messagingSenderId: '1070995801144',
    projectId: 'mengproject-9eb56',
    storageBucket: 'mengproject-9eb56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_K47Q4-GHUAvt5AZI2SA1G-7OsJufrc',
    appId: '1:1070995801144:ios:886b9fe3e49e64b84552cd',
    messagingSenderId: '1070995801144',
    projectId: 'mengproject-9eb56',
    storageBucket: 'mengproject-9eb56.appspot.com',
    iosBundleId: 'com.meng.kfaMobilenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi_K47Q4-GHUAvt5AZI2SA1G-7OsJufrc',
    appId: '1:1070995801144:ios:886b9fe3e49e64b84552cd',
    messagingSenderId: '1070995801144',
    projectId: 'mengproject-9eb56',
    storageBucket: 'mengproject-9eb56.appspot.com',
    iosBundleId: 'com.meng.kfaMobilenu',
  );
}
