// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCos70Q2c-MSrP-4qvBTHmAwYllT2CCvnE',
    appId: '1:758451633421:web:419a3771de060b555f0444',
    messagingSenderId: '758451633421',
    projectId: 'phone-otp-4b9ca',
    authDomain: 'phone-otp-4b9ca.firebaseapp.com',
    storageBucket: 'phone-otp-4b9ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjEwTxWp7RrzPHV-KcgXeM-F76Q9pFTN8',
    appId: '1:758451633421:android:9db385a12da7b5b95f0444',
    messagingSenderId: '758451633421',
    projectId: 'phone-otp-4b9ca',
    storageBucket: 'phone-otp-4b9ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzzr_0m4JrevxC-ePViz1hD1y0xYUIRQ',
    appId: '1:758451633421:ios:085c6e2c48d203615f0444',
    messagingSenderId: '758451633421',
    projectId: 'phone-otp-4b9ca',
    storageBucket: 'phone-otp-4b9ca.appspot.com',
    iosBundleId: 'com.meng.kfaMobilenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjzzr_0m4JrevxC-ePViz1hD1y0xYUIRQ',
    appId: '1:758451633421:ios:085c6e2c48d203615f0444',
    messagingSenderId: '758451633421',
    projectId: 'phone-otp-4b9ca',
    storageBucket: 'phone-otp-4b9ca.appspot.com',
    iosBundleId: 'com.meng.kfaMobilenu',
  );
}
